name: fam_works
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  #Firebase
  firebase_core: ^2.25.5
  firebase_auth: ^4.17.6
  firebase_storage: ^11.6.7
  cloud_firestore: ^4.15.6
  #Device Camera and Gallery
  image_picker: ^1.0.4
  intl: ^0.19.0
  #UI
  delightful_toast: ^1.1.0
  flutter_rating_bar: ^4.0.1
  flutter_map: ^6.1.0
  #Cache
  shared_preferences: ^2.2.0
  cached_network_image: ^3.3.1
  path_provider: ^2.1.1
  #State Management
  provider: ^6.1.2
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  #Network
  http: ^1.0.0
  connectivity_plus: ^5.0.2
  geolocator: ^11.0.0
  #Notification
  onesignal_flutter: ^5.1.2
  


  cupertino_icons: ^1.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  #Code Generation
  build_runner: ^2.4.8
  mobx_codegen: ^2.6.1


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
